### ISSUE TITLE
Cell Selection API 

### ISSUE THREAD

**Issue by gabrielmontagne** [zambezi/grid-components#2]
## Context

I'm working on cell selection, and trying to figure out which API would be the most useful -- or at least reasonably useful.

Thinking out loud, the "obvious" way (meaning the way that pops into my head first) would be something like: 

### Events

```javascript
const cellSelection = createCellSelection()
          .on('cell-selected-change', onCellSelected)
    , grid = createGrid()
          .use(cellSelection)
```

... where that `onCellSelected` would be called with an array of "cell objects"
which are basically `{ row, column }`, the references to the data, not some indices, as well as a couple of other hopefully useful props.

Basically, the object you'd get on the `cell-update`, `cell-enter`, etc. events, as [described here](https://github.com/zambezi/grid/blob/master/man/row-and-cell-events.md)

I think that the "geometric" (say) info about the x and y coordinates of the selection is not really useful -- one would use it to go back to the data and try to extract the `{ row, column }` etc. info that we'd be giving already.
Whoever needs to draw the cute border around the cell bundles can figure it out on its own.

One could, at any moment, check the selected cells by looking into a standard `getter/setter`

```javascript
component.selected() // ⇒ [{row, column}, {row, column}]
```

### Programmatic selection

This is the perhaps what's dimmer in my brain.

To be consistent with what was described above, one would immediately write...

```javascript
component.selected([{row, column}, {row, column}])
```

... the problem (which might not be a problem at all) with this is that the "cell objects" one gets from the grid have been "produced" internally by the grid when it transforms the original row data.  And this is JavaScript, and references are _sigh_ important.  So these wouldn't be "the same" you'd get from the grid -- even though they might be equivalent.
And some synthetic stuff that gets added (enriched with vitamin C) you don't, of course, need to provide.

### What could go wrong with this approach?

Perhaps one would like to check if a cell is selected?

Perhaps one doesn't have the column at hand to produce the `{row, column}` bundle?

What do you guys think? @mamapitufo, @mere, @janesconference, @pemrouz, @mstade

**Comment by mstade** [comment]
> And this is JavaScript, and references are sigh important.

For *objects*, but not values – can `row` and `column` be indices or some other value based key?

**Comment by gabrielmontagne** [comment]
I guess we could support the column _object_, but also the column _id_, which is a string.  
Rows don't have an id.  But we could, if we were going to go on this magic yellow brick road, also support index on the original data?

But if you have the references, pass them in (?).

The component would, when run, consolidate and normalize.  So what you would not be what you get back -- you'd get back the "real thing" after the next draw cycle.

Just don't want to keep arrays alternative arrays of indices and all that crap like in the old school Fl*x days.

**Comment by mstade** [comment]
Indices are like coordinates, they make it easy to pinpoint an exact *position* of a column and row, but it doesn't necessarily mean the `{column,row}` pair you expected will be in that position – which is obviously where indices fall short.

Some sort of id or key that's not equivalent to coordinates, but semantically tied to the content, are probably better but only if that key can be easily derived – but JS doesn't have any decent and cheap way of turning objects into such a hash, meaning there'd probably be a need for custom data structures which is not ideal. 

Lastly, the cell objects you mention may be the most semantically easy to reason about, but sounds like it may require potentially heavy lookup routines.

Does that about sum up it up fairly?

**Comment by gabrielmontagne** [comment]
Totally :^)   I'm sketching something up, will put it up here soon.

Another thing I'd forgotten, we'll probably need the concept of 'active' cell, the last one selected on a multiple or incremental selection.  Like in [blender](https://www.blender.org/manual/modeling/meshes/selecting/basics.html#adding-to-a-selection) :monkey_face:  ; )

**Comment by gabrielmontagne** [comment]
how about something like this?

https://github.com/zambezi/grid-components/compare/cell-selection-work
http://bl.ocks.org/gabrielmontagne/6291cffce1c783cb94e6f565fb185b3f

**Comment by mstade** [comment]
So I could do `cells.selected(rows[5], table.columns()[2])` and it would select the cell at row six, column three?

**Comment by gabrielmontagne** [comment]
Yeah, almost, it'd be an array, but yes, 

```javascript
cells.selected([{ row: rows[5], column: table.columns()[2] } /*, and potentially others */])
```     
The example doesn't yet show this, but it should already support (but should we?)    

```javascript
cells.selected([   ...    { row: 5, column: 'email' } ... ])
```  
... as well.   Where `5` is the index in the _original_, unsorted array you passed the grid, and `email` would be the column id -- which can be explicit, or is autogenerated from the _key_, or the _label_, or some random `gen-2343-whareva`.

**Comment by gabrielmontagne** [comment]
Created a PR with the proposed implementation. This can, of course, get infinitely fancier, but I think it's a good start.   Also, I've added a "select by index and column id" button on the [live example](http://bl.ocks.org/gabrielmontagne/6291cffce1c783cb94e6f565fb185b3f)

**Comment by gabrielmontagne** [comment]
I'll close this issue, we can continue the conversation in #3 .
